### ISSUE TITLE
Connections issues - none of my device will go 2-way

### ISSUE THREAD

**Issue by baldyman01** [slowscript/warpinator-android#149]
I have 1.82 installed on a Samsung S20, a Samsung Galaxy tab 5e,  two older Sony Xperia tablets, and my Linux Mint desktop. Things generally detect other things although this is not 100%, but nothing will go 2 way with anything else. I just end up with explanation marks. I've restarted everything and as it stands the S20 will go 2-way with the Desktop, one of the Sony's says it's 2 way with the Tab 5e but the other one won't and the Tab 5e just gives me explanation marks. 

I can't seem to find any logic as to what will connect to what when. How do I go about diagnosing this mess?

**Comment by vajdao** [comment]
Suffering from the same issue.. This so called program had been patched to oblivion but to no avail, it's just another FOSS mess. My PC (Linux Mint) and Android (Samsung Galaxy A52s 5G) keeps getting disconnected / unpaired on their own, sometimes in the middle of a transfer, while my phone's screen is not even locked, I also made sure to put this app on the whitelist so it won't get auto suspended on the phone, but to no avail, the app just kees acting as an old man with dementia, and sometimes even forcing pair with QR code solves the issue for a handful of 1minute, then it just unpairs again... 

I'm using LocalSend in the meantime, at least that one works (however that's slow as a slug, but still, works), but Warpinator would be the best because of the great speed it has.

**Comment by TwistedC0de** [comment]
I think it would be helpful if you guys can provide logs of your issues.

**Comment by baldyman01** [comment]
Yep LocalSend seems to be the answer. I have old and new android all interoperating correctly with my Linux desktop.

I'll have another go with Warpinator to see if I can get any logs out of it, but the difference with LocalSend is night and day.

**Comment by slowscript** [comment]
@vajdao Your unpairing issue could be caused by the system clocks running slightly out of sync and triggering a race condition in the connection keep-alive mechanism of gRPC. I have tweaked the keep-alive values in version 1.8.3, which should fix the problem if my guess is correct (I cannot know without a log).

@baldyman01 I would really need to see the logs of both sides that are having issues. There are instructions on how to get the logs in the recently updated [troubleshooting tips](https://slowscript.xyz/warpinator-android/connection-issues/#getting-the-debug-log).

**Comment by vajdao** [comment]
> @vajdao Your unpairing issue could be caused by the system clocks running slightly out of sync and triggering a race condition in the connection keep-alive mechanism of gRPC. I have tweaked the keep-alive values in version 1.8.3, which should fix the problem if my guess is correct (I cannot know without a log).

All my systems are hooked up with ntp timeserver including my phone, they are ticking on the same time, with absolute accuracy, like a metronome. The logs ain't generate in any way which is odd (I cannot provide one without generating itself)

1.8.3 have slightly better stability in terms of maintained connection, but still not as perfect as KDE Connect which stays connected with my PC - no matter what. I think it would be wise to look into their code for some inpspiration.

**Comment by alek3y** [comment]
Unfortunately the situation doesn't seem to have improved. Similarly to last time, neither connected to _navi_, _tea_ connected to _maple_ but not viceversa. The logs contain multiple attempts so I'd look at them starting from the bottom, as this situation happened at around 11:24.

Last time I copied `latest.log` (after closing the app) instead of using the "Save log" button, but it still seems to be cut off on 1.8.4. To make sure everything is included though, I'm sending the one exported with the button.

[maple.log](https://github.com/user-attachments/files/22719567/maple.log)
[tea.log](https://github.com/user-attachments/files/22719566/tea.log)

At the end of the logs for _tea_ there should also be a situation where the device would only list _maple_  and not _navi_, despite _maple_ being able to see it.

**Comment by slowscript** [comment]
Thanks for the good news, it sounds great but it's also strange 😅 I don't think I've changed anything that would fix such an issue. One possibility is that it's because it's a debug build. A release build has minification turned on, which removes what it thinks is unused code, but sometimes it removes too much and it crashes on some code paths. Here is a release build with the same changes: [warpinator-release.zip](https://github.com/user-attachments/files/22913284/warpinator-release.zip). The same changes (except logging) are now also pushed to master. If it still works, you don't need to send logs again.

As for discovery, I know it has some reliability issues. I will look into that next.

Removing the app from recents does the same as 'Quit' (unless you turn off 'Stop service after leaving app'), you can see 'Server stopped' right after 'Task removed' in the log. I think the connection reset is what was happening when navi was attempting to connect, but back then we did not have more detailed logs turned on, so who knows what is the cause. In the new logs it only appears when the other is not running, which is expected.

The ValueError happens because it needs one more change I originally forgot to mention (moving the `channel.subscribe()` line) and only edited it into the comment shortly before your reply. But since it seems to work now, this is does not matter.
